name: chinese_chess
description: 跨平台中国象棋
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.5.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: MaShanZheng
      fonts:
        - asset: assets/fonts/MaShanZheng.ttf
